### PR TITLE
UofT DSI | Sampling - Assignment 1 

### PR DESCRIPTION
**Pull request by lee-data**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Submitting Assignment 1.

## What did you learn from the changes you have made?
- Biased result when data are randomly sampled 
- How to simulate it with codes without having to pay expensively
- The importance of setting reproducibility 

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
N/A

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I cannot get the output to look like Whitby's graphs in the blog post. 

## How were these changes tested?
In Jupyter notebook. 

## A reference to a related issue in your repository (if applicable)
N/A

## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by KasraVakiloroayaei — CHANGES_REQUESTED** [review]
A1: Incomplete

Please make assignment visible to be read on markdown

**Comment by KasraVakiloroayaei** [comment]
Your solutions are fine. 
Unfortunately the Markdown file isn't displaying your solutions accordingly.
image

**Comment by lee-data** [comment]
> Your solutions are fine. Unfortunately the Markdown file isn't displaying your solutions accordingly. image

Hi Kasra, I have pasted the answers in the .md file, please check if it's okay now, thanks.

**Comment by KasraVakiloroayaei** [comment]
A1: Complete 

Thank you for making the update in the md. file

**Comment by lee-data** [comment]
> A1: Complete
> 
> Thank you for making the update in the md. file

Thank you Kasra, I'll close the Pull Request now.

**Pull request closed without merging**
